"""Shared application constants."""

MAX_TICKERS = 12
MIN_PERIOD_DAYS = 45
MIN_TRADING_ROWS = 30
WEIGHT_TOLERANCE_PCT = 0.5
LOADER_MIN_SECONDS = 2.5
LOADER_PAINT_DELAY = 0.15

TICKER_PATTERN = r"^(?=.*[A-Z0-9])[A-Z0-9.\-^=]{1,10}$"
