"""Loading overlay shown during portfolio analysis."""
from __future__ import annotations

MONEY_LOADER_HTML = (
    '<style>'
    '@keyframes fp-bounce{0%,100%{transform:translateY(0) rotate(-6deg) '
    'scale(1);}50%{transform:translateY(-30px) rotate(8deg) scale(1.08);}}'
    '@keyframes fp-fall{0%{transform:translateY(-15vh) rotate(0deg);opacity:0;}'
    '8%{opacity:0.55;}92%{opacity:0.55;}100%{transform:translateY(115vh) '
    'rotate(720deg);opacity:0;}}'
    '@keyframes fp-pulse-dot{0%,100%{opacity:0.35;transform:scale(0.7);}'
    '50%{opacity:1;transform:scale(1.3);}}'
    '@keyframes fp-glow{0%,100%{filter:drop-shadow(0 0 24px '
    'rgba(59,130,246,0.6));}50%{filter:drop-shadow(0 0 50px '
    'rgba(251,191,36,0.85));}}'
    '@keyframes fp-ring-spin{from{transform:rotate(0deg);}to{transform:'
    'rotate(360deg);}}'
    '.fp-overlay{position:fixed;top:0;left:0;width:100vw;height:100vh;'
    'background:radial-gradient(circle at center,rgba(15,23,42,0.94) 0%,'
    'rgba(2,6,23,0.99) 80%);-webkit-backdrop-filter:blur(12px);'
    'backdrop-filter:blur(12px);z-index:99999;display:flex;'
    'flex-direction:column;align-items:center;justify-content:center;'
    'overflow:hidden;pointer-events:none;}'
    '.fp-drop{position:absolute;top:0;font-size:30px;animation:fp-fall '
    '5s linear infinite;will-change:transform;}'
    '.fp-ring{position:absolute;width:220px;height:220px;border-radius:50%;'
    'border:2px dashed rgba(59,130,246,0.35);animation:fp-ring-spin '
    '18s linear infinite;}'
    '.fp-ring-2{width:300px;height:300px;border:1px dashed '
    'rgba(251,191,36,0.25);animation:fp-ring-spin 26s linear infinite reverse;}'
    '.fp-center{font-size:96px;animation:fp-bounce 1.6s ease-in-out infinite,'
    'fp-glow 2.6s ease-in-out infinite;z-index:2;line-height:1;}'
    '.fp-brand{font-size:34px;font-weight:900;color:#f8fafc;'
    'letter-spacing:-1.5px;margin-top:22px;z-index:2;}'
    '.fp-brand span{color:#3b82f6;}'
    '.fp-text{color:#94a3b8;font-size:14px;font-weight:500;margin-top:10px;'
    'z-index:2;letter-spacing:0.02em;}'
    '.fp-dots{display:flex;gap:8px;margin-top:18px;z-index:2;}'
    '.fp-dots span{width:9px;height:9px;border-radius:50%;background:#3b82f6;'
    'animation:fp-pulse-dot 1.4s ease-in-out infinite;}'
    '.fp-dots span:nth-child(2){animation-delay:0.2s;background:#fbbf24;}'
    '.fp-dots span:nth-child(3){animation-delay:0.4s;background:#10b981;}'
    '</style>'
    '<div class="fp-overlay">'
    '<span class="fp-drop" style="left:3%;animation-delay:0s;">💵</span>'
    '<span class="fp-drop" style="left:10%;animation-delay:1.3s;'
    'font-size:24px;">💰</span>'
    '<span class="fp-drop" style="left:17%;animation-delay:2.6s;">💸</span>'
    '<span class="fp-drop" style="left:24%;animation-delay:0.7s;'
    'font-size:36px;">💴</span>'
    '<span class="fp-drop" style="left:31%;animation-delay:3.1s;">💵</span>'
    '<span class="fp-drop" style="left:38%;animation-delay:1.9s;'
    'font-size:28px;">💶</span>'
    '<span class="fp-drop" style="left:62%;animation-delay:0.4s;">💷</span>'
    '<span class="fp-drop" style="left:69%;animation-delay:2.2s;'
    'font-size:34px;">💰</span>'
    '<span class="fp-drop" style="left:76%;animation-delay:3.7s;">💵</span>'
    '<span class="fp-drop" style="left:83%;animation-delay:0.95s;'
    'font-size:26px;">💸</span>'
    '<span class="fp-drop" style="left:90%;animation-delay:2.8s;">💴</span>'
    '<span class="fp-drop" style="left:97%;animation-delay:1.5s;'
    'font-size:30px;">💵</span>'
    '<div class="fp-ring"></div><div class="fp-ring fp-ring-2"></div>'
    '<div class="fp-center">💰</div>'
    '<div class="fp-brand">Fin<span>Port</span></div>'
    '<div class="fp-text">Analyzing your portfolio...</div>'
    '<div class="fp-dots"><span></span><span></span><span></span></div>'
    '</div>'
)
